AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Versant tfe Service

  Terraform Enterprise

Parameters:
  Domain:
    Type: String
    Description: 'Application Platform'

  System:
    Type: String
    Description: 'Application System'

  Component:
    Type: String
    Description: 'Application Component'

  CodeBranch:
    Type: String
    Description: 'Name of deployment branch'

  ClusterName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Name of ECS cluster

  ClusterAlbListenerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Name of ECS cluster

  ClusterSecurityGroupId:
    Type: AWS::SSM::Parameter::Value<String>
    Description: ID of cluster security group

  ContainerImage:
    Type: String
    Description: Container image

  ContainerTag:
    Type: String
    Description: Container tag

  ContainerCpu:
    Type: Number
    Description: Container CPU allocation units. 1024 is 1 CPU. Value may equal fraction of a CPU.

  ContainerMemory:
    Type: Number
    Description: Container memory in megabytes

  ContainerDesiredCount:
    Type: Number
    Description: How many copies of the service task to run

  EnableContainerExec:
    Type: String
    Description: Enable ECS Exec for the container
    AllowedValues:
      - "true"
      - "false"
    Default: "false"

  ContainerPort:
    Type: Number
    Description: Port container will listen on

  AlbRulePriority:
    Type: Number
    Description: The priority for the routing rule added to the load balancer.

  AlbRulePath:
    Type: String
    Description: A path on the public load balancer that this service
      should be connected to. Use * to send all load balancer
      traffic to this service.

  VpcId:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Account VPC ID


  VpcSubnets:
    Type: AWS::SSM::Parameter::Value<CommaDelimitedList>
    Description: Account subnets

#  DatadogApiKey:
#    Type: String
#    Description: Datadog API Key

  TfeDockerHubUsername:
    Type: String
    Description: TFE Docker Hub Username
    Default: 'terraform'

  TfeLicenseKey:
    Type: String
    Description: TFE License Key
    NoEcho: true

  RdsSecurityGroupId:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Security group ID for RDS access

  PgHost:
    Type: String
    Description: Postgres host

  PgPort:
    Type: Number
    Description: Postgres port

  PgDatabaseUser:
    Type: String
    Description: Postgres database user

  PgDatabasePassword:
    Type: String
    Description: Postgres database password
    NoEcho: true

  PgDatabaseParameters:
    Type: String
    Description: Postgres database connection parameters

  DatabaseName:
    Type: String
    Description: Postgres database name

  CacheSecurityGroupId:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Security group ID for cache access

  CacheEndpointAddress:
    Type: String
    Description: Cache endpoint address

  CachePort:
    Type: String
    Description: Cache port

  Hostname:
    Type: String
    Description: Site FQDN


Conditions:
  IsEnableContainerExec: !Equals [!Ref EnableContainerExec, "true"]

Resources:
  TfeObjectStorageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: RetainExceptOnCreate
    UpdateReplacePolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3

  TfeLicenseSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: RetainExceptOnCreate
    UpdateReplacePolicy: Retain
    Properties:
      Description: 'TFE License Key / Hashi Docker hub login'
      SecretString: !Sub |
        {
          "username": "${TfeDockerHubUsername}",
          "password": "${TfeLicenseKey}"
        }

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      Family: !Sub ${Component}-${CodeBranch}
      Cpu: !Ref ContainerCpu
      Memory: !Ref ContainerMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref ExecutionIamRole
      TaskRoleArn: !Ref TaskIamRole
      ContainerDefinitions:
        - Name: !Ref Component
          Image: !Sub '${ContainerImage}:${ContainerTag}'
          RepositoryCredentials:
            CredentialsParameter: !Ref TfeLicenseSecret
          Environment:
            - Name: TFE_HOSTNAME
              Value: !Ref Hostname
            - Name: TFE_OPERATIONAL_MODE
              Value: "active-active"
            - Name: TFE_DATABASE_HOST
              Value: !Sub "${PgHost}:${PgPort}"
            - Name: TFE_DATABASE_NAME
              Value: !Ref DatabaseName
            - Name: TFE_DATABASE_USER
              Value: !Ref PgDatabaseUser
            - Name: TFE_DATABASE_PASSWORD
              Value: !Ref PgDatabasePassword
            - Name: TFE_DATABASE_PARAMETERS
              Value: !Ref PgDatabaseParameters
            - Name: TFE_DATABASE_MONITOR_ENABLED
              Value: "true"
            - Name: TFE_REDIS_HOST
              Value: !Sub "${CacheEndpointAddress}:${CachePort}"
            - Name: TFE_OBJECT_STORAGE_TYPE
              Value: s3
            - Name: TFE_OBJECT_STORAGE_S3_BUCKET
              Value: !Ref TfeObjectStorageBucket
            - Name: TFE_OBJECT_STORAGE_S3_REGION
              Value: !Ref AWS::Region
            - Name: TFE_OBJECT_STORAGE_S3_USE_INSTANCE_PROFILE
              Value: true
          Secrets:
            - Name: TFE_LICENSE
              ValueFrom: !Sub "${TfeLicenseSecret}:password::"
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          DockerLabels:
            com.datadoghq.tags.domain: !Ref Domain
            com.datadoghq.tags.system: !Ref System
            com.datadoghq.tags.component: !Ref Component
            com.datadoghq.tags.code_branch: !Ref CodeBranch
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-group: !Sub '/aws/ecs/${ClusterName}/${AWS::StackName}'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: app
#        - Name: datadog-agent
#          Cpu: 256
#          Memory: 512
#          Image: 'public.ecr.aws/datadog/agent:latest'
#          Environment:
#            - Name: DD_API_KEY
#              Value: !Ref DatadogApiKey
#            - Name: ECS_FARGATE
#              Value: true
#            - Name: DD_LOG_LEVEL
#              Value: ERROR
#          HealthCheck:
#            Command:
#              - CMD-SHELL
#              - 'agent health'
#            Interval: 5
#            Retries: 3
#            StartPeriod: 10
#            Timeout: 5
#          LogConfiguration:
#            LogDriver: awslogs
#            Options:
#              awslogs-create-group: true
#              awslogs-group: !Sub '/aws/ecs/${ClusterName}/${AWS::StackName}/monitoring'
#              awslogs-region: !Ref AWS::Region
#              awslogs-stream-prefix: datadog


  Service:
    Type: AWS::ECS::Service
    DependsOn:
      - AlbListenerRule
      - CacheSecurityGroupIngress
      - RdsSgIngressRule
    Properties:
      ServiceName: !Ref Component
      Cluster: !Ref ClusterName
      LaunchType: FARGATE
      EnableECSManagedTags: true
      PropagateTags: TASK_DEFINITION
      EnableExecuteCommand: !Ref EnableContainerExec
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      DesiredCount: !Ref ContainerDesiredCount
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !Ref ClusterSecurityGroupId
          Subnets: !Ref VpcSubnets
          AssignPublicIp: ENABLED   # Enabled because this runs in public subnet
      TaskDefinition: !Ref TaskDefinition

      LoadBalancers:
        - ContainerName: !Ref Component
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref AlbTargetGroup
      HealthCheckGracePeriodSeconds: 60


  # IAM Roles
  # Governs permissions during task initialization
  ExecutionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: ECRImage
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'
                Resource: '*'
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
        - PolicyName: SecretsManagerRead
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'secretsmanager:GetSecretValue'
                Resource: !Ref TfeLicenseSecret


  # Governs permissions of running task container.
  TaskIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                Resource:
                  - !GetAtt TfeObjectStorageBucket.Arn
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:DeleteObject"
                Resource:
                  - !Sub '${TfeObjectStorageBucket.Arn}/*'

  ContainerExecIamPolicy:
    Type: AWS::IAM::Policy
    Condition: IsEnableContainerExec
    Properties:
      PolicyName: AllowECSExec
      Roles:
        - !Ref TaskIamRole
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - 'ssmmessages:CreateControlChannel'
              - 'ssmmessages:CreateDataChannel'
              - 'ssmmessages:OpenControlChannel'
              - 'ssmmessages:OpenDataChannel'
            Resource: '*'



  # ALB
  AlbTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 5
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 4
      HealthyThresholdCount: 2
      TargetType: ip
      Port: !Ref ContainerPort
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId: !Ref VpcId

  AlbListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref AlbTargetGroup
          Type: forward
      Conditions:
        - Field: path-pattern
          Values:
            - !Ref AlbRulePath
      ListenerArn: !Ref ClusterAlbListenerArn
      Priority: !Ref AlbRulePriority


  # Cache access
  CacheSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref CacheSecurityGroupId
      SourceSecurityGroupId: !Ref ClusterSecurityGroupId
      IpProtocol: tcp
      FromPort: !Ref CachePort
      ToPort: !Ref CachePort

  # DB access
  RdsSgIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref RdsSecurityGroupId
      IpProtocol: tcp
      FromPort: !Ref PgPort
      ToPort: !Ref PgPort
      SourceSecurityGroupId: !Ref ClusterSecurityGroupId